### ISSUE TITLE
Cancel button from "Open catalog" or "Import catalog from" popup window doesn't work and causes program to crash

### ISSUE THREAD

**Issue by WojtasJD** [wdlkmpx/gwhere#5]
GWhere version: 0.3.W.alpha
Distribution: GNU/Linux Lubuntu 22.04.1 x64 ; Arch Linux x64 with LXQt 1.0.0

Steps to reproduce:
1. Compile GWhere from git
2. Launch the program
3. Click "Open catalog" icon or select from menu: File -> Open 
4. From "Open catalog" popup window click "Cancel" button (nothing happens)
5. Click "Cancel" button again (program crashes)

or:
1. Compile GWhere from git
2. Launch the program
3. Select from menu: Import -> CSV catalog
4. From "Import catalog from" popup window click "Cancel" button (nothing happens)
5. Click "Cancel" button again (program crashes)

If you launch _gwhere_ from terminal emulator and it crashes you can see some error messages like:
corrupted double-linked list
Aborted (core dumped)

or:
Segmentation fault (core dumped)

or:
double free or corruption (fasttop)
Aborted (core dumped)

or:
malloc_consolidate(): unaligned fastbin chunk detected
Aborted (core dumped)

**Comment by wdlkmpx** [comment]
Thanks for reporting the bug in such detail, it should be fixed now

I'm thinking of integrating this app into what I call `wgtkdesk`, just because all gtk apps require the same helper functions and stuff, and it really takes forever to update and fix each app individually
https://github.com/wdlkmpx/wgtkdesk

**Comment by WojtasJD** [comment]
Nice... Thank you!
It's working.
